
platform :ios, '9.0'

target 'SelfUse' do
  use_frameworks!

pod 'Alamofire', '= 4.7.1'
pod 'SDWebImage', '= 4.3.3'
pod 'Masonry', '= 1.1.0'
pod 'SwiftyJSON', '= 4.0.0'
pod 'UIColor_Hex_Swift', '= 4.0.1'
pod 'LQCCategory', '= 2.0.2'



end
